#!/bin/bash

podman rm -f opa
podman run --rm -d  \
       -v $(pwd)/policy.rego:/policy/policy.rego \
       --network host \
       --name "opa" \
       -e METRICS_SERVICE_HOST=$(host $(hostname) | awk ' { print $NF }') \
       -e METRICS_SERVICE_PORT=8080 \
       docker.io/openpolicyagent/opa:latest-envoy \
       run --server --addr=0.0.0.0:8181 \
       --diagnostic-addr=0.0.0.0:8282 \
       --set=plugins.envoy_ext_authz_grpc.addr=:9191 \
       --set=plugins.envoy_ext_authz_grpc.query=data.envoy.authz.allow \
       --set=decision_logs.console=true \
       --ignore=".*" \
       /policy/policy.rego
